# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.10.5
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.5

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest pytest-cov scikit-learn pathos lange scipy numpy Cython
          pip install -e .
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 src --count --select=E9,F63,F7,F82 --show-source --statistics --ignore E741
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 src --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics --ignore E741

      - name: Test with pytest
        run: |
          pytest src tests --cov=src --doctest-modules

      - name: Generates coverage.xml
        run: |
          coverage xml

      - name: Upload reports to codecov
        env:
          CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
        run: | 
          curl -Os https://uploader.codecov.io/latest/linux/codecov
          find . -iregex "codecov.*"
          chmod +x codecov 
          ./codecov -t ${CODECOV_TOKEN}

#      - name: Upload coverage to Codecov
#        uses: codecov/codecov-action@v2
#        with:
#          files: ./coverage.xml
#          token: ${{ secrets.CODECOV_TOKEN }}
#          fail_ci_if_error: true
#          verbose: true
